import { integer, pgEnum, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const orderStatus = pgEnum("order_status", ["new", "production", "ready", "shipped", "delivered", "cancelled"]);
export const paymentStatus = pgEnum("payment_status", ["pending", "paid", "refunded"]);

export const users = pgTable("users", { id: uuid("id").defaultRandom().primaryKey(), email: text("email").notNull().unique(), passwordHash: text("password_hash").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const sessions = pgTable("sessions", { id: text("id").primaryKey(), userId: uuid("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull() });
export const customers = pgTable("customers", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), email: text("email"), phone: text("phone"), address: text("address"), postalCode: text("postal_code"), city: text("city"), country: text("country").default("Portugal"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const products = pgTable("products", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), description: text("description"), priceCents: integer("price_cents").notNull(), stock: integer("stock").notNull().default(0), imageUrl: text("image_url"), active: integer("active").notNull().default(1), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const orders = pgTable("orders", { id: uuid("id").defaultRandom().primaryKey(), orderNumber: integer("order_number").notNull().unique(), customerId: uuid("customer_id").references(() => customers.id).notNull(), status: orderStatus("status").default("new").notNull(), payment: paymentStatus("payment").default("pending").notNull(), orderDate: timestamp("order_date", { withTimezone: true }).defaultNow().notNull(), deliveryDate: timestamp("delivery_date", { withTimezone: true }), shippingMethod: text("shipping_method"), address: text("address"), notes: text("notes"), totalCents: integer("total_cents").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const orderItems = pgTable("order_items", { id: uuid("id").defaultRandom().primaryKey(), orderId: uuid("order_id").references(() => orders.id, { onDelete: "cascade" }).notNull(), productId: uuid("product_id").references(() => products.id).notNull(), productName: text("product_name").notNull(), unitPriceCents: integer("unit_price_cents").notNull(), quantity: integer("quantity").notNull(), totalCents: integer("total_cents").notNull() });
export const orderStatusHistory = pgTable("order_status_history", { id: uuid("id").defaultRandom().primaryKey(), orderId: uuid("order_id").references(() => orders.id, { onDelete: "cascade" }).notNull(), fromStatus: orderStatus("from_status"), toStatus: orderStatus("to_status").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
